# Generated by Django 4.2.6 on 2023-11-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='waiting_for_player',
            field=models.BooleanField(default=True),
        ),
    ]
