# Generated by Django 4.2.6 on 2023-11-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_opponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='symbol_creator',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='symbol_opponent',
            field=models.URLField(blank=True, null=True),
        ),
    ]
