# Generated by Django 4.2.6 on 2023-11-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_symbol_creator_game_symbol_opponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_turn',
            field=models.CharField(choices=[('creator', 'player1'), ('opponent', 'player2')], max_length=10, null=True),
        ),
    ]
