# Generated by Django 4.2.6 on 2023-11-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_current_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='board_state',
            field=models.TextField(default='[]'),
        ),
    ]
