# Generated by Django 4.2.6 on 2023-12-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_game_board_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='current_turn',
        ),
        migrations.AddField(
            model_name='game',
            name='current_player',
            field=models.CharField(default='', max_length=50),
        ),
    ]
