# Generated by Django 4.2.6 on 2023-12-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_remove_game_current_turn_game_current_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='surrender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
